collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.09505906
color:
  saturation: 0.4425594
  brandStrength: 0.3432247
  rhythmicContrast: 0.8536653
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 0.8690802
layout_spectrum: 1
name: 'Undiscovered Star Entertainment. '
