layout_spectrum: 1
color:
  saturation: 0.4425594
  lightness: 0.8690802
  brandStrength: 0.3432247
  rhythmicContrast: 0.8536653
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.8533874
name: 'Undiscovered Star Entertainment. '
