collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.09505906
color:
  saturation: 0.3249194
  brandStrength: 0.3432247
  lightness: 0.5655209
  brandColors:
    - '#EAA760'
    - '#FFFFFF'
    - '#030303'
    - '#E12101'
    - '#7E2225'
  rhythmicContrast: 0.5601504
layout_spectrum: 1
name: 'Undiscovered Star Entertainment. '
